<script type="text/javascript">
//<![CDATA[
  if (typeof (EloomCorreiosSro) == "undefined") {
    var EloomCorreiosSro = Class.create();
  }
  EloomCorreiosSro.prototype = {
    initialize: function() {
    },
    tracking: function(fieldId, number) {
      new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/*/tracking') ?>', {
        asynchronous: true,
        method: 'post',
        parameters: {id: fieldId, number: number},
        onSuccess: this._onSuccess.bindAsEventListener(this, fieldId)
      });
    },
    _onSuccess: function(transport, fieldId) {
      var response = null;
      if (transport && transport.responseText) {
        try {
          response = eval('(' + transport.responseText + ')');
        } catch (e) {
          response = {};
        }
      }
      var div = $('tracking-result-' + fieldId).update('');
      if (response.status == 'success') {
        var track = response.track;

        div.insert(new Element('p').update(track.status));
        div.insert(new Element('p').update('Em: ' + track.deliverydate + ' às: ' + track.deliverytime));
        div.insert(new Element('p').update('Local: ' + track.deliverylocation));
      } else {
        div.update(new Element('p').update(response.message));
      }
    },
  };

  var eloomCorreiosSroInst = new EloomCorreiosSro();
//]]>
</script>